trigger:
  - master
  - dev

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

jobs:
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: 'build/run-build.yml'
  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - template: 'build/run-build.yml'
  - job: MacOS
    pool:
      vmImage: "macos-10.13"
    steps:
      - template: 'build/run-build.yml'
  - job: Deploy
    dependsOn:
      - Windows
      - MacOS
      - Linux
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: DownloadPipelineArtifact@1
        displayName: Download Artifacts from other jobs
        inputs:
          buildType: 'current'
      - task: GitHubRelease@0
        displayName: Upload CLI releases to Github
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          gitHubConnection: "release"
          repositoryName: "intiface/intiface-desktop"
          action: "create"
          tagSource: "auto"
          title: "Buttplug JS CLI Release"
          assets: "$(System.ArtifactsDirectory)/**/*"
          isPreRelease: false
