trigger:
  branches:
    include:
      - master
      - dev
  tags:
    include:
      - v*

jobs:
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: 'build/setup-variables.yml'
      - template: 'build/setup-signing-key.yml'
      - template: 'build/run-build.yml'
        parameters:
          platform: "win"
  # - job: Linux
  #   pool:
  #     vmImage: "ubuntu-16.04"
  #   steps:
  #     - template: 'build/run-build.yml'
  #       parameters:
  #         platform: "linux"
  # - job: MacOS
  #   pool:
  #     vmImage: "macos-10.13"
  #   steps:
  #     - template: 'build/run-build.yml'
  #       parameters:
  #         platform: "macos"
  - job: Deploy
    dependsOn:
      - Windows
      # - MacOS
      # - Linux
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: DownloadPipelineArtifact@1
        displayName: Download Artifacts from other jobs
        inputs:
          buildType: 'current'
      - task: GitHubRelease@0
        displayName: Upload release to Github
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
          gitHubConnection: "release"
          repositoryName: "intiface/intiface-desktop"
          action: "create"
          tagSource: "auto"
          title: "Intiface Desktop Release $(gitVersion)"
          assets: "$(System.ArtifactsDirectory)/**/*"
          isPreRelease: false
