trigger:
  - master
  - dev

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'
- script: |
    yarn
    yarn build:all
  displayName: 'yarn install and build'
- task: CopyFiles@2
  displayName: "Copy frozen executables to staging"
  inputs:
    sourceFolder: "$(System.DefaultWorkingDirectory)/packages/intiface-desktop/dist_electron"
    contents: "intiface-desktop-*"
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
- task: PublishPipelineArtifact@0
  displayName: "Publish frozen executables to artifacts"
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'intiface-desktop-$(imageName)'
